/*SECUENCIAS*/
CREATE SEQUENCE seq_sede START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_docente START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_ciclo START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_modulo START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_estudiante START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_matricula START WITH 1 INCREMENT BY 1 NOCACHE;

/*SEDE*/
INSERT INTO SEDE VALUES (seq_sede.NEXTVAL, 'Sede Central', 'Gran Via', 10, '912345678');
INSERT INTO SEDE VALUES (seq_sede.NEXTVAL, 'Sede Norte', 'Alcala', 25, '913333333');
INSERT INTO SEDE VALUES (seq_sede.NEXTVAL, 'Sede Sur', 'Av. Andalucia', 50, '914444444');

/*DOCENTE*/
INSERT INTO DOCENTE VALUES (seq_docente.NEXTVAL,'12345678A','NSS001','Juan','Perez','Lopez','600111222',1);
INSERT INTO DOCENTE VALUES (seq_docente.NEXTVAL,'87654321B','NSS002','Ana','Gomez',NULL,'600333444',2);
INSERT INTO DOCENTE VALUES (seq_docente.NEXTVAL,'33445566E','NSS003','Carlos','Ruiz','Molina','600555666',3);
INSERT INTO DOCENTE VALUES (seq_docente.NEXTVAL,'99887766F','NSS004','Laura','Fernandez',NULL,'600777888',1);

/*CICLO sysdate aprendido con explicacion de gemini basada en esta documentacion: https://docs.oracle.com/en/database/oracle/oracle-database/26/sqlrf/SYSDATE.html*/
INSERT INTO CICLO_FORMATIVO VALUES (seq_ciclo.NEXTVAL,'DAW','Primero',SYSDATE,ADD_MONTHS(SYSDATE,9),1);
INSERT INTO CICLO_FORMATIVO VALUES (seq_ciclo.NEXTVAL,'ASIR','Segundo',SYSDATE,ADD_MONTHS(SYSDATE,9),2);
INSERT INTO CICLO_FORMATIVO VALUES (seq_ciclo.NEXTVAL,'DAM','Primero',SYSDATE,ADD_MONTHS(SYSDATE,9),3);
INSERT INTO CICLO_FORMATIVO VALUES (seq_ciclo.NEXTVAL,'SMR','Segundo',SYSDATE,ADD_MONTHS(SYSDATE,9),1);

/*MODULO*/
INSERT INTO MODULO VALUES (seq_modulo.NEXTVAL,'Bases de Datos','DAW','Modelo relacional y SQL',180,1);
INSERT INTO MODULO VALUES (seq_modulo.NEXTVAL,'Sistemas Operativos','ASIR','Administración de sistemas',200,2);
INSERT INTO MODULO VALUES (seq_modulo.NEXTVAL,'Programacion','DAM','Java y POO',220,3);
INSERT INTO MODULO VALUES (seq_modulo.NEXTVAL,'Redes','SMR','Redes locales',160,4);

/*CONTIENE*/
INSERT INTO CONTIENE VALUES (1,1);
INSERT INTO CONTIENE VALUES (2,2);
INSERT INTO CONTIENE VALUES (3,3);
INSERT INTO CONTIENE VALUES (4,4);

/*ESTUDIANTE*/
INSERT INTO ESTUDIANTE VALUES (seq_estudiante.NEXTVAL,'Luis','Martinez','Ruiz','11111111C');
INSERT INTO ESTUDIANTE VALUES (seq_estudiante.NEXTVAL,'Maria','Sanchez',NULL,'22222222D');
INSERT INTO ESTUDIANTE VALUES (seq_estudiante.NEXTVAL,'Pedro','Lopez','Garcia','33333333E');
INSERT INTO ESTUDIANTE VALUES (seq_estudiante.NEXTVAL,'Lucia','Navarro',NULL,'44444444F');

/*MATRICULA*/
INSERT INTO MATRICULA VALUES (seq_matricula.NEXTVAL,'2024/2025',SYSDATE,'Matricula DAW',1,1);
INSERT INTO MATRICULA VALUES (seq_matricula.NEXTVAL,'2024/2025',SYSDATE,'Matricula ASIR',2,2);
INSERT INTO MATRICULA VALUES (seq_matricula.NEXTVAL,'2024/2025',SYSDATE,'Matricula DAM',3,3);
INSERT INTO MATRICULA VALUES (seq_matricula.NEXTVAL,'2024/2025',SYSDATE,'Matricula SMR',4,4);

/*CURSA*/
INSERT INTO CURSA VALUES (1,1);
INSERT INTO CURSA VALUES (2,2);
INSERT INTO CURSA VALUES (3,3);
INSERT INTO CURSA VALUES (4,4);

/*ADHIERE*/
INSERT INTO ADHIERE VALUES (1,1);
INSERT INTO ADHIERE VALUES (2,2);
INSERT INTO ADHIERE VALUES (3,3);
INSERT INTO ADHIERE VALUES (4,4);

/*NOTAS*/
INSERT INTO NOTAS VALUES (1,1,7.50);
INSERT INTO NOTAS VALUES (1,2,8.00);
INSERT INTO NOTAS VALUES (2,1,6.25);
INSERT INTO NOTAS VALUES (3,1,5.75);

/*DEPENDE*/
INSERT INTO DEPENDE VALUES (4,1);

